// Student dashboard surfacing invites, attendance history, and QR check-in.
import { useState, useEffect, useCallback, useRef } from 'react';
import { Layout } from '@/components/Layout';
import { EventCard } from '@/components/EventCard';
import { QRScanner } from '@/components/QRScanner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { CalendarDays, CheckCircle, QrCode, Star, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Event, EventInvitation } from '@/types';
import { apiService } from '@/services/api';
import { useAuth } from '@/contexts/AuthContext';
import { Textarea } from '@/components/ui/textarea';

export default function StudentDashboard() {
  const { user } = useAuth();
  const [showQRScanner, setShowQRScanner] = useState(false);
  const [upcomingEvents, setUpcomingEvents] = useState<Event[]>([]);
  const [attendedEvents, setAttendedEvents] = useState<Event[]>([]);
  const [invitations, setInvitations] = useState<EventInvitation[]>([]);
  const [feedbackDialogOpen, setFeedbackDialogOpen] = useState(false);
  const [pendingFeedbackEvent, setPendingFeedbackEvent] = useState<Event | null>(null);
  const [feedbackRating, setFeedbackRating] = useState(5);
  const [feedbackComments, setFeedbackComments] = useState('');
  const [feedbackSubmitting, setFeedbackSubmitting] = useState(false);
  const dismissedFeedbackRef = useRef<Set<string>>(new Set());
  const feedbackClosedBySubmitRef = useRef(false);
  const [stats, setStats] = useState({
    attendedEvents: 0,
    upcomingEvents: 0,
    feedbackGiven: 0
  });
  const { toast } = useToast();

  // Pull upcoming events, tracked attendance, and pending invites.
  const loadData = useCallback(async () => {
    if (!user) return;
    
    try {
      const [allEvents, attendanceData, statsData, invitationData] = await Promise.all([
        apiService.getEvents(),
        apiService.getStudentAttendance(user.id),
        apiService.getStudentStats(user.id),
        apiService.getMyInvitations(),
      ]);

      const now = new Date();
      const upcoming = allEvents.filter(event => new Date(event.date) > now && event.approval_status === 'approved');
      
      setUpcomingEvents(upcoming);
      setAttendedEvents(attendanceData.events);
      setStats(statsData);
      setInvitations(invitationData.filter((inv) => inv.status === 'pending'));
    } catch (error) {
      console.error('Failed to load student data:', error);
    }
  }, [user]);

  useEffect(() => {
    if (user) {
      loadData();
    }
  }, [user, loadData]);

  useEffect(() => {
    if (!user) return;
    const interval = setInterval(() => {
      loadData();
    }, 60000);
    return () => clearInterval(interval);
  }, [user, loadData]);

useEffect(() => {
  const pendingIds = new Set(
    attendedEvents
      .filter(
        (event) =>
          event.status === 'completed' &&
          event.feedback_open &&
          !event.feedback_submitted
      )
      .map((event) => event.id)
  );
  const toRemove: string[] = [];
  dismissedFeedbackRef.current.forEach((id) => {
    if (!pendingIds.has(id)) {
      toRemove.push(id);
    }
  });
  toRemove.forEach((id) => dismissedFeedbackRef.current.delete(id));
  if (feedbackDialogOpen) return;
  const next = attendedEvents.find(
    (event) =>
      event.status === 'completed' &&
      event.feedback_open &&
      !event.feedback_submitted &&
      !dismissedFeedbackRef.current.has(event.id)
  );
  if (next) {
    setPendingFeedbackEvent(next);
    setFeedbackDialogOpen(true);
  }
}, [attendedEvents, feedbackDialogOpen]);

  // Mark attendance after a successful scan and refresh the dashboard.
  const handleQRScanSuccess = async ({ eventId, code }: { eventId: string; code?: string }) => {
    if (!user) return;
    if (!code) {
      toast({
        title: 'Code required',
        description: 'Please scan the official QR code generated by the coordinator.',
        variant: 'destructive'
      });
      return;
    }
    
    setShowQRScanner(false);
    try {
      await apiService.markAttendance(eventId, {
        code,
        registrationId: user.registration_id,
      });
      toast({
        title: "Attendance Marked!",
        description: `Successfully marked attendance for event.`
      });
      // Refresh data
      loadData();
    } catch (error: unknown) {
      toast({
        title: "Error",
        description: (error instanceof Error ? error.message : "Failed to mark attendance"),
        variant: "destructive"
      });
    }
  };

  // Accept or decline coordinator invitations directly from the dashboard.
  const handleInvitationResponse = async (invitation: EventInvitation, decision: 'accepted' | 'declined') => {
    try {
      await apiService.respondToInvitation(invitation.id, decision);
      toast({
        title: decision === 'accepted' ? 'Invitation accepted' : 'Invitation declined',
        description: decision === 'accepted'
          ? 'Great! You are confirmed for the event.'
          : 'The coordinator has been notified of your decision.'
      });
      loadData();
    } catch (error) {
      toast({
        title: 'Unable to update invitation',
        description: error instanceof Error ? error.message : 'Please try again later.',
        variant: 'destructive'
      });
    }
  };

  const statsDisplay = [
    { label: 'Upcoming Events', value: stats.upcomingEvents, icon: CalendarDays, color: 'bg-primary' },
    { label: 'Events Attended', value: stats.attendedEvents, icon: CheckCircle, color: 'bg-success' },
    { label: 'Feedback Given', value: stats.feedbackGiven, icon: Star, color: 'bg-accent' }
  ];

const handleFeedbackDialogChange = (open: boolean) => {
  setFeedbackDialogOpen(open);
  if (!open) {
    if (!feedbackClosedBySubmitRef.current && pendingFeedbackEvent) {
      dismissedFeedbackRef.current.add(pendingFeedbackEvent.id);
    }
    setPendingFeedbackEvent(null);
    setFeedbackComments('');
    setFeedbackRating(5);
    feedbackClosedBySubmitRef.current = false;
  }
};

  const handleSubmitFeedback = async () => {
    if (!pendingFeedbackEvent) return;
    setFeedbackSubmitting(true);
    try {
      await apiService.submitFeedback({
        event_id: pendingFeedbackEvent.id,
        rating: feedbackRating,
        comments: feedbackComments.trim(),
      });
      toast({
        title: 'Feedback submitted',
        description: `Thanks for sharing feedback for ${pendingFeedbackEvent.title}.`,
      });
      feedbackClosedBySubmitRef.current = true;
      dismissedFeedbackRef.current.add(pendingFeedbackEvent.id);
      setFeedbackDialogOpen(false);
      setPendingFeedbackEvent(null);
      setFeedbackComments('');
      setFeedbackRating(5);
      loadData();
    } catch (error) {
      toast({
        title: 'Unable to submit feedback',
        description: error instanceof Error ? error.message : 'Please try again later.',
        variant: 'destructive',
      });
    } finally {
      setFeedbackSubmitting(false);
    }
  };

return (
  <>
    <Layout title="Student Dashboard">
      <div className="space-y-6">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-3xl font-bold">Student Dashboard</h1>
            <p className="text-muted-foreground">Discover and attend college events</p>
          </div>
          <Dialog open={showQRScanner} onOpenChange={setShowQRScanner}>
            <DialogTrigger asChild>
              <Button className="gap-2">
                <QrCode className="w-4 h-4" />
                Scan QR Code
              </Button>
            </DialogTrigger>
            <DialogContent className="w-full max-w-md sm:max-w-lg">
              <DialogHeader>
                <DialogTitle>Mark Attendance</DialogTitle>
              </DialogHeader>
              <QRScanner onScanSuccess={handleQRScanSuccess} />
            </DialogContent>
          </Dialog>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {statsDisplay.map((stat) => (
            <Card key={stat.label} className="bg-gradient-card shadow-card border-0">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className={`w-12 h-12 rounded-lg ${stat.color} flex items-center justify-center`}>
                    <stat.icon className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">{stat.value}</p>
                    <p className="text-sm text-muted-foreground">{stat.label}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {invitations.length > 0 && (
          <Card className="bg-gradient-card shadow-card border-0">
            <CardHeader>
              <CardTitle>Pending Invitations</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {invitations.map((invitation) => {
                const matchingEvent = [...upcomingEvents, ...attendedEvents].find((event) => event.id === invitation.event_id);
                return (
                <div
                  key={invitation.id}
                  className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 border rounded-lg p-3"
                >
                  <div>
                    <p className="font-medium">{matchingEvent?.title || 'Event invitation'}</p>
                    <p className="text-xs text-muted-foreground">
                      Invited as {invitation.role_at_event === 'coordinator' ? 'Coordinator' : 'Attendee'}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {matchingEvent ? new Date(matchingEvent.date).toLocaleString() : `Event ID: ${invitation.event_id}`}
                    </p>
                    {matchingEvent && (
                      <div className="mt-1 flex flex-wrap gap-2 text-xs">
                        <Badge variant="outline" className="capitalize">{matchingEvent.approval_status}</Badge>
                        <Badge variant="outline" className="capitalize">{matchingEvent.delivery_mode.replace('-', ' ')}</Badge>
                      </div>
                    )}
                    {invitation.message && (
                      <p className="text-xs mt-1">“{invitation.message}”</p>
                    )}
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleInvitationResponse(invitation, 'declined')}
                    >
                      Decline
                    </Button>
                    <Button
                      size="sm"
                      onClick={() => handleInvitationResponse(invitation, 'accepted')}
                    >
                      Accept
                    </Button>
                  </div>
                </div>
              );
              })}
            </CardContent>
          </Card>
        )}

        <Card className="bg-gradient-card shadow-card border-0">
          <CardHeader>
            <CardTitle>Upcoming Events</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {upcomingEvents.map((event) => (
                <EventCard
                  key={event.id}
                  event={event}
                  onViewDetails={() => console.log('View details:', event.id)}
                />
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-card shadow-card border-0">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              Attended Events
              <Badge variant="secondary">{attendedEvents.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {attendedEvents.map((event) => (
                <div key={event.id} className="relative">
                  <EventCard
                    event={event}
                    onViewDetails={() => console.log('View details:', event.id)}
                  />
                  <div className="absolute top-2 right-2">
                    <Badge className="bg-success text-success-foreground">
                      <CheckCircle className="w-3 h-3 mr-1" />
                      Attended
                    </Badge>
                  </div>
                </div>
              ))}
              {attendedEvents.length === 0 && (
                <p className="text-center text-muted-foreground py-8 col-span-2">
                  No events attended yet
                </p>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
    <Dialog open={feedbackDialogOpen} onOpenChange={handleFeedbackDialogChange}>
      <DialogContent className="w-full max-w-lg">
        <DialogHeader>
          <DialogTitle>Share feedback</DialogTitle>
          {pendingFeedbackEvent && (
            <p className="text-sm text-muted-foreground">
              {pendingFeedbackEvent.title} • {new Date(pendingFeedbackEvent.date).toLocaleString()}
            </p>
          )}
        </DialogHeader>
        {pendingFeedbackEvent ? (
          <div className="space-y-5">
            <div className="space-y-2">
              <p className="text-sm font-medium">Overall experience</p>
              <div className="flex gap-2">
                {[1, 2, 3, 4, 5].map((value) => (
                  <Button
                    key={value}
                    type="button"
                    variant={feedbackRating === value ? 'default' : 'outline'}
                    size="sm"
                    className="h-9 w-9 rounded-full p-0"
                    onClick={() => setFeedbackRating(value)}
                  >
                    {value}
                  </Button>
                ))}
              </div>
            </div>
            <div className="space-y-2">
              <p className="text-sm font-medium">Highlights or suggestions</p>
              <Textarea
                value={feedbackComments}
                onChange={(e) => setFeedbackComments(e.target.value)}
                rows={4}
                placeholder="Share what went well and what can improve."
              />
            </div>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">Loading event info…</p>
        )}
        <DialogFooter className="gap-2 sm:gap-0">
          <Button
            type="button"
            variant="outline"
            onClick={() => handleFeedbackDialogChange(false)}
            disabled={feedbackSubmitting}
            className="w-full sm:w-auto"
          >
            Maybe later
          </Button>
          <Button
            type="button"
            onClick={handleSubmitFeedback}
            disabled={feedbackSubmitting || !pendingFeedbackEvent}
            className="gap-2 w-full sm:w-auto"
          >
            {feedbackSubmitting && <Loader2 className="h-4 w-4 animate-spin" />}
            Submit feedback
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </>
);
}
