name: Azure CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-ci-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./event-management-backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: event-management-backend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: unipalacr3940.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./event-management-backend
        push: true
        tags: unipalacr3940.azurecr.io/event-backend:latest
        platforms: linux/amd64

    - name: Deploy to Azure Web App
      run: |
        curl -X POST ${{ secrets.WEBAPP_WEBHOOK }}

  frontend-ci-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./event-management-frontend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: event-management-frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Build React App
      run: npm run build
      env:
        VITE_API_URL: https://unipal-backend-3940.azurewebsites.net

    - name: Upload to Azure Storage
      run: |
        az storage blob upload-batch --account-name unipalfe3940 --source ./dist --destination '$web' --overwrite --connection-string "${{ secrets.STORAGE_CONNECTION_STRING }}"
